# Generated by Django 5.1.2 on 2024-10-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_suggestion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='user',
        ),
    ]
