# Generated by Django 5.1.2 on 2024-10-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('last_activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='history',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='review',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
