# Generated by Django 5.1.2 on 2024-10-23 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='review',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
