# Generated by Django 5.1.2 on 2024-10-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dishes',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
