# Generated by Django 5.1.2 on 2024-10-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_review_downvotes_remove_review_upvotes_and_more'),
        ('main', '0003_initial'),
    ]

    operations = [
    ]
