# Generated by Django 5.1.2 on 2024-10-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_restaurant_dish_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
